version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: payitc-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payitc
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - payitc-network

  auth-service:
    build: ./auth-service
    container_name: payitc-auth
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/payitc
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8081:8080"
    networks:
      - payitc-network

  payment-service:
    build: ./payment-service
    container_name: payitc-payment
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/payitc
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8082:8080"
    networks:
      - payitc-network

volumes:
  mysql_data:

networks:
  payitc-network: