CREATE DATABASE IF NOT EXISTS payitc;
USE payitc;

CREATE TABLE merchants (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    callback_url VARCHAR(255) NOT NULL,
    status ENUM('ACTIVE','INACTIVE') DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE transactions (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    merchant_id BIGINT,
    reference_code VARCHAR(150),
    amount DECIMAL(15,2),
    currency VARCHAR(10) DEFAULT 'COP',
    state ENUM('CREATED','PENDING','APPROVED','REJECTED') DEFAULT 'CREATED',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);